version: "3.9"

services:
  github_resume:
    build:
      context: .
    container_name: github_resume
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_PORT: 5672
    networks:
      - git_resume_network


networks:
  git_resume_network:
    name: git_resume_network
    external: true
